### PR TITLE
Remove duplicate globals code

### PR DESCRIPTION
**Pull request by ksunden**

### CODE REVIEW

**Comment by ksunden** [comment]
In all honesty, I am of the opinion that SimpleGlobal should go away entirely, it does _nothing_ that a simple variable doesn't do (though some of the subclasses/related things do add some behavior to read/write... I think those should be functions, not classes)

Globals do not do anything for thread safety, there are no locks or anything.
Most of the globals which are used are set at start up and never changed.

Most of these should be constants/variables located in the relevant subsection of the code, rather than "globally" accessible (for some, like app and main_thread, the relevant subsection is simply `_pycmds.py`, I believe... though perhaps a smaller project globals can persist, to avoid circular imports.

**Comment by ksunden** [comment]
Converted to draft because I went back to rerun and it crashes...

I suspect one of the "unused" ones was hidden in its use, will have to look again at those... thought I had run it at each step, but just went to run and it crashed

**Comment by ksunden** [comment]
Relatively concerning... the `scan_thread` was what was responsible for it failing to start... it is written but never read, so project globals must be what is preventing it from getting garbage collected or something.

Perhaps we should add back in the daq widget for the same reason... though that is getting removed soon anyway, soooo

**Comment by ksunden** [comment]
I think with daq_widget being removed, I have no further concerns at all about this branch, the only things actually removed were never touched at all... I do have concerns about scan_thread and why that seems to be garbage collected or something without it's global, but that behavior is not changed here...

**Comment by untzag** [comment]
@ksunden are you saying we should merge or no?

**Comment by ksunden** [comment]
@untzag yes, though I bet it is easier to fix the merge conflicts (if they should present, which they might not, as both delete daq_widget) with #291 here, so I would do it after that one is merged

**Comment by ksunden** [comment]
Merge conflicts resolved

**Review by untzag — APPROVED** [review]

**Pull request merged**
