### PR TITLE
lab weather station device

### PR DESCRIPTION
**Pull request by ksunden**
A simple minimum viable implementation of a PyCMDS "device"
which talks to the "lab weather station"

The firmware loaded simply prints comma separated temp,humidity,pressure
upon recieving serial input.

I did not do anything involving shots (though there may have been some parts that snuck through)

### CODE REVIEW

**Comment by darienmorrow** [comment]
When switching between devices on PyCMDS the `environmental_sensor` device name is a bit long. Can we change it to something shorter? Maybe `envi_sensor`?

**Comment by untzag** [comment]
@ksunden what's the plan with this PR?

**Comment by ksunden** [comment]
The conflict is trivial (blackening is what caused it)

We never really did come to a conclusion on a rename, which is why it's been stagnant, it works otherwise.

The other consideration is that this sensor is a good candidate for yaqifying.

**Comment by ksunden** [comment]
(Actually, that conflict was the file being deleted, the change in it is no longer needed)

**Comment by ksunden** [comment]
Closing as we intend to switch to yaq (or mqtt) for this kind of sensor before it becomes truly useful... we can always restore if we absolutely need it...

**Pull request closed without merging**
